/*{"version":"11839230","created":"2012-07-22T19:41:45Z","k":"0.16.1","mac":"1:e5ea6c93d68565f23d7022bcd1514fd2feb7e923e986cc952acfe9b32664b097"}*/
;(function(window,document,undefined){
var g=void 0,l=!0,n=null,o=!1;function p(a){return function(){return this[a]}}var q;function r(a,c,b){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return c.apply(a,d)}}function s(a){this.m=a;this.w=g}s.prototype.createElement=function(a,c,b){a=this.m.createElement(a);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?this.pa(a,c[d]):a.setAttribute(d,c[d]));b&&a.appendChild(this.m.createTextNode(b));return a};
function t(a,c,b){a=a.m.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function u(a){function c(){document.body?a():setTimeout(c,0)}c()}function v(a){a.parentNode&&a.parentNode.removeChild(a)}function w(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}
function x(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function y(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return l;return o}s.prototype.pa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};s.prototype.U=function(){if(this.w===g){var a=this.m.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};
function z(a,c,b,d,e,f,h){this.W=a;this.Pa=c;this.wa=b;this.va=d;this.Ka=e;this.Ja=f;this.ua=h}q=z.prototype;q.getName=p("W");q.getVersion=p("Pa");q.getEngine=p("wa");q.getEngineVersion=p("va");q.getPlatform=p("Ka");q.getPlatformVersion=p("Ja");q.getDocumentMode=p("ua");function aa(a,c){this.c=a;this.v=c}var ba=new z("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
aa.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE"))if(a=A(this.c,/(MSIE [\d\w\.]+)/,1),""!=a){var c=a.split(" ");a=c[0];c=c[1];a=new z(a,c,a,c,B(this),C(this),D(this.v),6<=E(c))}else a=new z("MSIE","Unknown","MSIE","Unknown",B(this),C(this),D(this.v));else if(-1!=this.c.indexOf("Opera"))a:{var c=a="Unknown",b=A(this.c,/(Presto\/[\d\w\.]+)/,1);""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=A(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b));if(-1!=this.c.indexOf("Version/")&&
(b=A(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new z("Opera",b,a,c,B(this),C(this),D(this.v),10<=E(b));break a}b=A(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new z("Opera",b,a,c,B(this),C(this),D(this.v),10<=E(b)):new z("Opera","Unknown",a,c,B(this),C(this),D(this.v))}else if(-1!=this.c.indexOf("AppleWebKit")){a=B(this);c=C(this);b=A(this.c,/AppleWebKit\/([\d\.]+)/,1);""==b&&(b="Unknown");var d="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")?d="Chrome":-1!=this.c.indexOf("Safari")?
d="Safari":-1!=this.c.indexOf("AdobeAIR")&&(d="AdobeAIR");var e="Unknown";-1!=this.c.indexOf("Version/")?e=A(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==d?e=A(this.c,/(Chrome|CrMo)\/([\d\.]+)/,2):"AdobeAIR"==d&&(e=A(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(A(e,/\d+\.(\d+)/,1),2<E(e)||E(e)):(A(b,/\d+\.(\d+)/,1),526<=E(b)||E(b));a=new z(d,e,"AppleWebKit",b,a,c,D(this.v))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";d=o;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=A(this.c,/Firefox\/([\d\w\.]+)/,
1),""!=b&&(d=A(b,/\d+\.(\d+)/,1),c=b,d=""!=b&&3<=E(b)&&5<=parseInt(d,10))):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla");b=A(this.c,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!d){var d=E(b),e=parseInt(A(b,/\d+\.(\d+)/,1),10),f=parseInt(A(b,/\d+\.\d+\.(\d+)/,1),10);1<d||1==d&&9<e||1==d&&9==e&&2<=f||b.match(/1\.9\.1b[123]/)!=n||b.match(/1\.9\.1\.[\d\.]+/)}a=new z(a,c,"Gecko",b,B(this),C(this),D(this.v))}else a=ba;return a};
function B(a){var c=A(a.c,/(iPod|iPad|iPhone|Android)/,1);if(""!=c)return c;a=A(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}function C(a){var c=A(a.c,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=A(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;return(a=A(a.c,/Linux ([i\d]+)/,1))?a:"Unknown"}function E(a){a=A(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function A(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}
function D(a){if(a.documentMode)return a.documentMode}function ca(a,c,b){this.j=a;this.l=c;this.$=b;this.p="wf";this.n=new fa("-")}function ga(a){x(a.l,a.n.k(a.p,"loading"));y(a.l,a.n.k(a.p,"active"))||w(a.l,a.n.k(a.p,"inactive"));F(a,"inactive")}function F(a,c,b,d){if(a.$[c])a.$[c](b,d)}function H(a,c,b,d,e){this.j=a;this.A=c;this.C=b;this.u=d;this.G=e;this.O=0;this.qa=this.ia=o}
H.prototype.watch=function(a,c,b,d,e){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.O+=c[i].length}e&&(this.ia=e);for(h=0;h<f;h++)for(var i=a[h],e=c[i],j=b[i],k=0,m=e.length;k<m;k++){var da=e[k],G=this.A,P=i,ea=da;w(G.l,G.n.k(G.p,P,ea,"loading"));F(G,"fontloading",P,ea);G=r(this,this.xa);P=r(this,this.ya);(new d(G,P,this.j,this.C,this.u,this.G,i,da,j)).start()}};
H.prototype.xa=function(a,c){var b=this.A;x(b.l,b.n.k(b.p,a,c,"loading"));x(b.l,b.n.k(b.p,a,c,"inactive"));w(b.l,b.n.k(b.p,a,c,"active"));F(b,"fontactive",a,c);this.qa=l;ha(this)};H.prototype.ya=function(a,c){var b=this.A;x(b.l,b.n.k(b.p,a,c,"loading"));y(b.l,b.n.k(b.p,a,c,"active"))||w(b.l,b.n.k(b.p,a,c,"inactive"));F(b,"fontinactive",a,c);ha(this)};
function ha(a){0==--a.O&&a.ia&&(a.qa?(a=a.A,x(a.l,a.n.k(a.p,"loading")),x(a.l,a.n.k(a.p,"inactive")),w(a.l,a.n.k(a.p,"active")),F(a,"active")):ga(a.A))}
function I(a,c,b,d,e,f,h,i,j){this.sa=a;this.Ca=c;this.j=b;this.C=d;this.u=e;this.G=f;this.Ia=new ia;this.Aa=new ja;this.Q=h;this.P=i;this.za=j||"BESbswy";this.ja=ka(this,"arial,'URW Gothic L',sans-serif");this.ka=ka(this,"Georgia,'Century Schoolbook L',serif");this.ga=this.ja;this.ha=this.ka;this.X=J(this,"arial,'URW Gothic L',sans-serif");this.Y=J(this,"Georgia,'Century Schoolbook L',serif")}I.prototype.start=function(){this.Na=this.G();this.aa()};
I.prototype.aa=function(){var a=this.C.T(this.X),c=this.C.T(this.Y);(this.ja!=a||this.ka!=c)&&this.ga==a&&this.ha==c?(a=this.sa,v(this.X),v(this.Y),a(this.Q,this.P)):5E3<=this.G()-this.Na?(a=this.Ca,v(this.X),v(this.Y),a(this.Q,this.P)):(this.ga=a,this.ha=c,la(this))};function la(a){a.u(function(a,b){return function(){b.call(a)}}(a,a.aa),25)}function ka(a,c){var b=J(a,c,l),d=a.C.T(b);v(b);return d}function J(a,c,b){c=a.j.createElement("span",{style:ma(a,c,a.P,b)},a.za);t(a.j,"body",c);return c}
function ma(a,c,b,d){b=a.Aa.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(d?"":a.Ia.quote(a.Q)+",")+c+";"+b}function fa(a){this.Ga=a||"-"}fa.prototype.k=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ga)};function ia(){this.oa="'"}
ia.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");-1==d.indexOf(" ")?c.push(d):c.push(this.oa+d+this.oa)}return c.join(",")};function ja(){this.ma=na;this.D=oa}var na=["font-style","font-weight"],oa={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function pa(a,c,b){this.Da=a;this.La=c;this.D=b}pa.prototype.expand=function(a,c){for(var b=0;b<this.D.length;b++)if(c==this.D[b][0]){a[this.Da]=this.La+":"+this.D[b][1];break}};ja.prototype.expand=function(a){if(2!=a.length)return n;for(var c=[n,n],b=0,d=this.ma.length;b<d;b++){var e=this.ma[b];(new pa(b,e,this.D[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":n};function K(a){this.m=a;this.w=g}K.prototype=s.prototype;K.prototype.Ba=function(){return this.m.location.hostname};
function qa(a,c,b){var d=a.m.getElementsByTagName("head")[0];if(d){var e=a.m.createElement("script");e.src=c;var f=o;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=l,b&&b(),e.onload=e.onreadystatechange=n,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e)}}K.prototype.pa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};
K.prototype.U=function(){if(this.w===g){var a=this.m.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};function L(a,c){this.Ma=a;this.ba=c}function ra(a){for(var c=a.Ma.join(","),b=[],d=0;d<a.ba.length;d++){var e=a.ba[d];b.push(e.name+":"+e.value+";")}return c+"{"+b.join("")+"}"}function M(a,c){this.B=a;this.F=c;this.da={};this.ca={}}M.prototype.z=function(a){return a?(this.da[a.H]||this.F).slice(0):this.F.slice(0)};
function sa(a,c,b){for(var d=[],e=a.B.split(",")[0].replace(/"|'/g,""),f=a.z(),h,i=[],j={},k=0;k<f.length;k++)h=f[k],0<h.length&&!j[h]&&(j[h]=l,i.push(h));b=b.na?b.na(e,i,d):i;c=c.H;a.da[c]=b;a.ca[c]=d}M.prototype.watch=function(a,c,b){var d=[],e={};ta(this,c,d,e);a(d,e,b)};function ta(a,c,b,d){b.push(a.B);d[a.B]=a.z(c);a=a.ca[c.H]||[];for(c=0;c<a.length;c++){for(var e=a[c],f=e.B,h=o,i=0;i<b.length;i++)b[i]==f&&(h=l);h||(b.push(f),d[f]=e.z())}}function ua(a,c){this.B=a;this.F=c}ua.prototype.z=p("F");
function va(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=n}}function N(a,c){this.H=a;this.fa=c}function O(a){wa.K.push(a)}function xa(a){this.j=a;this.r=this.c=this.J=n;this.ta=this.Ea=this.Fa=l;this.o=[];this.L=[];this.ra=this.R=this.M=this.N=n}function Q(a){R.o.push(a)}function S(a){R.L.push(a)}
function ya(a,c){a.c=c;if(a.J){var b;a:{b=a.J;for(var d=a.c,e=a.Fa,f=a.Ea,h=a.ta,i=0;i<b.K.length;i++){var j=b.K[i];if(j.fa&&j.fa(d.getName(),d.getVersion(),d.getEngine(),d.getEngineVersion(),d.getPlatform(),d.getPlatformVersion(),d.getDocumentMode(),e,f,h)){b=j;break a}}b=n}a.r=b}}q=xa.prototype;q.supportsConfiguredBrowser=function(){return!!this.r};
q.init=function(){for(var a=[],c=0;c<this.L.length;c++)a.push(ra(this.L[c]));var c=this.j,a=a.join(""),b=this.j.m.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));t(c,"head",b)};
q.load=function(a,c){var b=this.r.H;if(this.R)for(var d=za(this.R,b),e=0;e<this.o.length;e++)sa(this.o[e],this.r,d);this.N&&(d=[],this.M&&(d=new Aa(this.j,this.r,this.o),d=Ba(this.M,b,d)),b=this.N.k("https:"==this.j.m.location.protocol,Ca(b,d)),t(this.j,"head",this.j.createElement("link",{rel:"stylesheet",href:b})));a&&u(function(a,b,c,e){return function(){for(var d=0;d<a.o.length;d++)a.o[d].watch(b,c,e&&d==a.o.length-1)}}(this,a,this.r,c))};
q.collectFontFamilies=function(a,c){for(var b=0;b<this.o.length;b++)ta(this.o[b],this.r,a,c)};q.performOptionalActions=function(a){this.V&&u(function(a,b,d,e){return function(){var b=a.V;if(b.la){var h=window.__adobewebfontsappname__,h=h?h.toString().substr(0,20):"";va(b.la.k("https:"==e.m.location.protocol,{host:encodeURIComponent(e.m.location.hostname),app:encodeURIComponent(h),_:(+new Date).toString()}))}b=a.V;b.Z&&(b=b.Z.k(d,e),t(e,"body",b))}}(this,a,this.c,this.j))};
function T(a,c,b,d){this.Ha=a;this.j=c;this.l=b;this.u=d;this.q=[]}T.prototype.I=function(a){this.q.push(a)};T.prototype.load=function(a,c){var b=a,d=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)d=b||{},b=[];if(b.length)for(var e=this,f=b.length,h=0;h<b.length;h++)Da(this,b[h],function(){0==--f&&Ea(e,d)});else Ea(this,d)};function Da(a,c,b){qa(a.j,a.Ha.k("https:"==a.j.m.location.protocol,{id:encodeURIComponent(c)}),b)}
function Ea(a,c){for(var b=new ca(a.j,a.l,c),d=o,e=0;e<a.q.length;e++)a.q[e].init(),d=d||a.q[e].supportsConfiguredBrowser();d?(w(b.l,b.n.k(b.p,"loading")),F(b,"loading"),Fa(a,b)):ga(b);a.q=[]}function Fa(a,c){function b(a,b,c){d.watch(a,b,{},I,c)}for(var d=new H(a.j,c,{T:function(a){return a.offsetWidth}},a.u,function(){return+new Date}),e=0;e<a.q.length;e++){var f=a.q[e];f.supportsConfiguredBrowser()&&(f.load(b,e==a.q.length-1),f.performOptionalActions(window))}}
function U(a,c){this.ea=a;this.u=c;this.q=[]}U.prototype.I=function(a){this.q.push(a)};U.prototype.load=function(){var a=this.ea.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],d=a[b.ra];if(d){var e=this.u;d(function(a,c,d){var c=[],j={};ya(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(n,e),b.collectFontFamilies(c,j),b.performOptionalActions(window));d(b.supportsConfiguredBrowser(),c,j)})}}};function V(a,c){this.W=a;this.na=c}V.prototype.getName=p("W");
function Ga(a){var c=W;Ha(c,a.getName())||c.S.push(a)}function Ha(a,c){for(var b=0;b<a.S.length;b++){var d=a.S[b];if(c===d.getName())return d}return n}function za(a,c){var b=a.s[c];return b?Ha(a,b):n}function Ba(a,c,b){for(var d=[],a=a.t[c]||[],c=0;c<a.length;c++){var e;a:switch(a[c]){case "observeddomain":e=new Ia(b.j);break a;case "fontmask":e=new Ja(b.r,b.o);break a;default:e=n}e&&d.push(e)}return d}function Aa(a,c,b){this.j=a;this.r=c;this.o=b}function Ia(a){this.j=a}
Ia.prototype.toString=function(){return encodeURIComponent(this.j.Ba?this.j.m.location.hostname:document.location.hostname)};function Ja(a,c){this.r=a;this.o=c}Ja.prototype.toString=function(){for(var a=[],c=0;c<this.o.length;c++)for(var b=this.o[c],d=b.z(),b=b.z(this.r),e=0;e<d.length;e++){var f;a:{for(f=0;f<b.length;f++)if(d[e]===b[f]){f=l;break a}f=o}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(d=a.length;0<d;d-=4)b=a.slice(0>d-4?0:d-4,d),c.unshift(parseInt(b,2).toString(16));return c.join("")};
function X(a){this.Oa=a}X.prototype.k=function(a,c){var b=c||{},d=this.Oa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,d){return d&&b[c]?"/"+b[c].join("/"):b[c]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function Ca(a,c){for(var b=[],d=0;d<c.length;d++)b.push(c[d].toString());return{format:a,extras:b}}var wa=new function(){this.K=[]};
O(new N("a",function(a,c,b,d,e,f){if(o||("Windows"==e&&"Unknown"==f?l:o)||("Ubuntu"==e||"Linux"==e?l:o))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=o}else a=o;return a}));
O(new N("b",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("a",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);
return!m&&!("Ubuntu"==e||"Linux"==e?l:o)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var d=parseFloat(c[1]),e=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=d)&&(4<d||4==d&&249<e||4==d&&249==e&&4<=c))return l}}return o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("d",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=(m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,
k))||("Ubuntu"==e||"Linux"==e?l:o)||function(a,b,c,e,d,f,h,i,j,k){a=/([0-9]+).([0-9]+)/.exec(f);return k&&"Android"==d&&a?(d=parseInt(a[1],10),k=parseInt(a[2],10),3==d&&1<=k||3<d):o}(a,c,b,d,e,f,h,i,j,k);return!(m||"CrOS"==e)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return l}}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("a",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,k);return!m&&!("Ubuntu"==e||"Linux"==e?l:o)?o:function(a,b,c,e){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(e)&&!a.test(e)):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("b",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b,c,e){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(e)&&!a.test(e)):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("d",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);
return!m&&!("Ubuntu"==e||"Linux"==e?l:o)?o:function(a,b,c,e){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("i",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b,c,e,d,f,h){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(h===g||9>h):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("d",function(a,c,b,d,e,f,h){if(!(c=o))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==e&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=o;a=c||("Windows"==e&&"6.0"==f?l:o)?"MSIE"==a?9<=h:g:o;return a}));
O(new N("a",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,k);return!m&&!("Ubuntu"==e||"Linux"==e?l:o)?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("b",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("d",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);
return!m&&!("Ubuntu"==e||"Linux"==e?l:o)?o:"Opera"==a?11.1<=parseFloat(c):o}));O(new N("b",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("a",function(a,c,b,d,e,f,h,i,j,k){var m;m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,k);return!m?o:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("d",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=o||("Windows"==e&&"5.1"==f?l:o)||("Windows"==e&&"5.2"==f?l:o)||("Windows"==e&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,d,e,f,h,i,j,k);
return!m?o:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?534.5<=parseFloat(a[1]):o}(a,c,b,d,e,f,h,i,j,k)}));
O(new N("a",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=(m=o||function(a,b,c,e,d,f,h,i,k,j){a=/([0-9]+).([0-9]+)/.exec(f);return j&&"Android"==d&&a?(d=parseInt(a[1],10),j=parseInt(a[2],10),2==d&&2<=j||3==d&&1>j):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,e,d,f,h,i,j){return j&&"iPad"==d&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,e,d,f,h,i){if(i&&("iPhone"==d||"iPod"==d))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],
10),4==parseInt(a[1],10)&&2<=b;return o}(a,c,b,d,e,f,h,i,j,k);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?l:o}));O(new N("f",function(a,c,b,d,e,f,h,i,j,k){if(!(c=o))f=/([0-9]+).([0-9]+)/.exec(f),k&&"Android"==e&&f?(k=parseInt(f[1],10),f=parseInt(f[2],10),c=3==k&&1<=f||3<k):c=o;return!c?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?l:o}));
O(new N("d",function(a,c,b,d,e,f,h,i,j,k){var m;m=(m=o||function(a,b,c,d,e,f,h,i,j){return j&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,d,e,f,h,i,j,k))||function(a,b,c,e,d,f,h,i){return i&&("iPhone"==d||"iPod"==d)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,d,e,f,h,i,j,k);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?l:o}));var W=new function(){this.S=[];this.s={}};
Ga(new V("AllFonts",function(a,c){return c}));
Ga(new V("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var d=0;d<c.length;d++){var e=c[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;b.push(new ua(f,[e]))}a={};for(e=0;e<c.length;e++)b=c[e],d=b.charAt(1),(a[d]||(a[d]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<b.length;e++)for(var f=b[e],h=0;h<f.length;h++){var i=f[h];if(a[i]){d=d.concat(a[i]);break}}b=d;d={};a=[];for(e=0;e<b.length;e++)f=b[e],d[f]||(d[f]=l,a.push(f));b=[];for(d=0;d<c.length;d++){e=c[d];
for(f=0;f<a.length;f++)h=a[f],h==e&&b.push(h)}return b}));W.s.a="AllFonts";W.s.b="AllFonts";W.s.d="AllFonts";W.s.e="AllFonts";W.s.f="AllFonts";W.s.g="AllFonts";W.s.h="AllFonts";W.s.i="DefaultFourFontsWithSingleFvdFamilies";var Y=new function(){this.t={}};Y.t.a=[];Y.t.b=[];Y.t.d=[];Y.t.e=[];Y.t.f=["observeddomain"];Y.t.g=["observeddomain"];Y.t.h=["observeddomain"];Y.t.i=["observeddomain","fontmask"];window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ka=function(a,c){setTimeout(a,c)},Z=new T(new X("//use.typekit.net/{id}.js"),new K(document),document.documentElement,Ka),$=new U(window,Ka);window.Typekit.load=function(){Z.load.apply(Z,arguments)};window.Typekit.addKit=function(){Z.I.apply(Z,arguments)}}var La,R;La=new function(){this.la=this.Z=n};R=new xa(new K(document));R.ra="cag5cie";R.N=new X("//use.typekit.net/k/cag5cie-{format}.css?3bb2a6e53c9684ffdc9a9bf61b5b2a628b788d2543d3caa13a870367dcc42ad6acd0bade2b54211e8e960e300bf36faf2e4f92e06527f9c9065245f8ee0c1dac25eda2510fd7927cb854ccb1798ddfc2e2528ba49e6846df5262b95b07fdebc159ca2ad437");
R.V=La;Q(new M("freight-sans-pro",["n4","n5","n6"]));Q(new M("ubuntu-mono",["n4"]));Q(new M("inconsolata",["n5"]));Q(new M("sax-mono",["n4"]));Q(new M("anonymous-pro",["n4"]));S(new L([".tk-freight-sans-pro"],[{name:"font-family",value:'"freight-sans-pro",sans-serif'}]));S(new L([".tk-ubuntu-mono"],[{name:"font-family",value:'"ubuntu-mono",sans-serif'}]));S(new L([".tk-inconsolata"],[{name:"font-family",value:'"inconsolata",sans-serif'}]));S(new L([".tk-sax-mono"],[{name:"font-family",value:'"sax-mono",monospace'}]));
S(new L([".tk-anonymous-pro"],[{name:"font-family",value:'"anonymous-pro",sans-serif'}]));R.J=wa;R.M=Y;R.R=W;$&&$.ea.__webfonttypekitmodule__?($.I(R),$.load()):(ya(R,(new aa(navigator.userAgent,document)).parse()),window.Typekit.addKit(R));
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=cag5cie&ht=tk&h={host}&f=10954.13460.13458.14534.126.42.579&a=187823&_={_}"};
/*{"k":"1.8.3","created":"2014-05-07 13:43:21 UTC"}*/
;(function(window,document,undefined){
function e(a){return function(){return this[a]}}var f=this;function h(a,b){var d=a.split("."),c=f;!(d[0]in c)&&c.execScript&&c.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&void 0!==b?c[g]=b:c=c[g]?c[g]:c[g]={}}function k(a,b,d){this.M=a;this.K=b;this.L=d}h("webfont.BrowserInfo",k);k.prototype.A=e("M");k.prototype.hasWebFontSupport=k.prototype.A;k.prototype.B=e("K");k.prototype.hasWebKitFallbackBug=k.prototype.B;k.prototype.C=e("L");k.prototype.hasWebKitMetricsBug=k.prototype.C;
function l(a,b,d,c,g,j,u,v,w,x,y){this.D=a;this.R=b;this.J=d;this.o=c;this.P=g;this.n=j;this.G=u;this.Q=v;this.F=w;this.m=x;this.k=y}h("webfont.UserAgent",l);l.prototype.getName=e("D");l.prototype.getName=l.prototype.getName;l.prototype.z=e("J");l.prototype.getVersion=l.prototype.z;l.prototype.s=e("o");l.prototype.getEngine=l.prototype.s;l.prototype.t=e("n");l.prototype.getEngineVersion=l.prototype.t;l.prototype.v=e("G");l.prototype.getPlatform=l.prototype.v;l.prototype.w=e("F");
l.prototype.getPlatformVersion=l.prototype.w;l.prototype.r=e("m");l.prototype.getDocumentMode=l.prototype.r;l.prototype.q=e("k");l.prototype.getBrowserInfo=l.prototype.q;function m(a){this.f=a}m.prototype.toString=function(){return encodeURIComponent(this.f.c.location.hostname||this.f.e.location.hostname)};function n(a,b){this.H=a;this.g=b}
n.prototype.toString=function(){for(var a=[],b=0;b<this.g.length;b++)for(var d=this.g[b],c=d.u(),d=d.u(this.H),g=0;g<c.length;g++){var j;a:{for(j=0;j<d.length;j++)if(c[g]===d[j]){j=!0;break a}j=!1}a.push(j?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(c=a.length;0<c;c-=4)d=a.slice(0>c-4?0:c-4,c),b.unshift(parseInt(d,2).toString(16));return b.join("")};function p(a){this.I=a}
p.prototype.l=function(a,b){var d=b||{},c=this.I.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,c){return c&&d[b]?"/"+d[b].join("/"):d[b]||""});c.match(/^\/\//)&&(c=(a?"https:":"http:")+c);return c.replace(/\/*\?*($|\?)/,"$1")};function q(a){var b=new Image(1,1);b.src=a;b.onload=function(){b.onload=null}}var r={};r.a=r.j=r.b=r.d=function(){return[]};r.i=function(a,b,d){return[new m(a),new n(b,d)]};window.Typekit||(window.Typekit={});
var s=new function(a,b){this.e=a;this.c=b||a;this.O=this.c.document}(window),t=new function(){var a=new p(window.Typekit.config.p);this.N=null;this.h=a},z=!1;
function A(){if(!z)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var d=a[b].getAttribute("href");if(d&&0<=d.indexOf("use.typekit")){a=t;b=s;if(a.h){var d=(d=window.__adobewebfontsappname__)?d.toString().substr(0,20):"",c=b.c.location.protocol;"about:"==c&&(c=b.e.location.protocol);q(a.h.l("https:"===("https:"==c?"https:":"http:"),{host:encodeURIComponent(b.c.location.hostname||b.e.location.hostname),app:encodeURIComponent(d),_:(+new Date).toString()}))}z=!0;break}}}var B=window.Typekit.load;
window.Typekit.load=function(){B&&B.apply(window.Typekit,arguments);A()};window.__webfonttypekitmodule__&&A();
})(this,document);
